site_name: Kubernetes Adoption Journey
site_url: !ENV [SITE_URL, "https://digitalocean.github.io/k8s-adoption-journey/"]
site_description: Hands-on tutorial for going from day-1 to production on DigitalOcean Kubernetes.
copyright: DigitalOcean
repo_url: "https://github.com/digitalocean/k8s-adoption-journey"
docs_dir: !ENV [DOCS_DIR, "docs"]
site_dir: !ENV [SITE_DIR, "site"]

nav:
  - Home: index.md
  - Getting started:
      - Installing the required tools: getting-started/installing-required-tools.md
      - Authentication: getting-started/authentication.md
      - Creating a Digital Ocean Kubernetes Cluster: getting-started/setting-up-a-digital-ocean-kubernetes-cluster.md
      - Creating a Digital Ocean Container Registry: getting-started/setting-up-a-digital-ocean-container-registry.md
      - Testing the setup: getting-started/testing-the-setup.md

theme:
  name: material
  logo: assets/do_logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  # simplifies relative linking between documents
  # https://github.com/midnightprioriem/mkdocs-autolinks-plugin
  - autolinks
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
